// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod docs {
    pub mod game_engine {
        /// Game state and world definitions.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Game actions the player can perform.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum GameAction {
                /// Move in a direction.
                MoveNorth,
                MoveSouth,
                MoveEast,
                MoveWest,
                /// Attack with current weapon.
                Attack,
                /// Use an item from inventory.
                UseItem,
                /// Open inventory menu.
                OpenInventory,
                /// Interact with environment/NPC.
                Interact,
                /// Wait/skip turn.
                Wait,
                /// Quit the game.
                Quit,
            }
            impl ::core::fmt::Debug for GameAction {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        GameAction::MoveNorth => {
                            f.debug_tuple("GameAction::MoveNorth").finish()
                        }
                        GameAction::MoveSouth => {
                            f.debug_tuple("GameAction::MoveSouth").finish()
                        }
                        GameAction::MoveEast => {
                            f.debug_tuple("GameAction::MoveEast").finish()
                        }
                        GameAction::MoveWest => {
                            f.debug_tuple("GameAction::MoveWest").finish()
                        }
                        GameAction::Attack => {
                            f.debug_tuple("GameAction::Attack").finish()
                        }
                        GameAction::UseItem => {
                            f.debug_tuple("GameAction::UseItem").finish()
                        }
                        GameAction::OpenInventory => {
                            f.debug_tuple("GameAction::OpenInventory").finish()
                        }
                        GameAction::Interact => {
                            f.debug_tuple("GameAction::Interact").finish()
                        }
                        GameAction::Wait => f.debug_tuple("GameAction::Wait").finish(),
                        GameAction::Quit => f.debug_tuple("GameAction::Quit").finish(),
                    }
                }
            }
            impl GameAction {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> GameAction {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => GameAction::MoveNorth,
                        1 => GameAction::MoveSouth,
                        2 => GameAction::MoveEast,
                        3 => GameAction::MoveWest,
                        4 => GameAction::Attack,
                        5 => GameAction::UseItem,
                        6 => GameAction::OpenInventory,
                        7 => GameAction::Interact,
                        8 => GameAction::Wait,
                        9 => GameAction::Quit,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Current game phase.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum GamePhase {
                /// Exploring the world.
                Exploration,
                /// In combat with an enemy.
                Combat,
                /// Viewing inventory.
                Inventory,
                /// Talking to NPC or reading sign.
                Dialogue,
                /// Game is paused.
                Paused,
                /// Game over (player defeated).
                GameOver,
                /// Victory (boss defeated).
                Victory,
            }
            impl ::core::fmt::Debug for GamePhase {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        GamePhase::Exploration => {
                            f.debug_tuple("GamePhase::Exploration").finish()
                        }
                        GamePhase::Combat => f.debug_tuple("GamePhase::Combat").finish(),
                        GamePhase::Inventory => {
                            f.debug_tuple("GamePhase::Inventory").finish()
                        }
                        GamePhase::Dialogue => {
                            f.debug_tuple("GamePhase::Dialogue").finish()
                        }
                        GamePhase::Paused => f.debug_tuple("GamePhase::Paused").finish(),
                        GamePhase::GameOver => {
                            f.debug_tuple("GamePhase::GameOver").finish()
                        }
                        GamePhase::Victory => {
                            f.debug_tuple("GamePhase::Victory").finish()
                        }
                    }
                }
            }
            impl GamePhase {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> GamePhase {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => GamePhase::Exploration,
                        1 => GamePhase::Combat,
                        2 => GamePhase::Inventory,
                        3 => GamePhase::Dialogue,
                        4 => GamePhase::Paused,
                        5 => GamePhase::GameOver,
                        6 => GamePhase::Victory,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Result of processing a game action.
            #[derive(Clone)]
            pub struct ActionResult {
                /// Whether the action was successful.
                pub success: bool,
                /// Description of what happened.
                pub message: _rt::String,
                /// New game phase after action.
                pub new_phase: GamePhase,
                /// Whether the game should continue.
                pub game_continues: bool,
            }
            impl ::core::fmt::Debug for ActionResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ActionResult")
                        .field("success", &self.success)
                        .field("message", &self.message)
                        .field("new-phase", &self.new_phase)
                        .field("game-continues", &self.game_continues)
                        .finish()
                }
            }
            /// Complete game state snapshot.
            #[derive(Clone)]
            pub struct GameState {
                /// Current game phase.
                pub phase: GamePhase,
                /// Player's current X position.
                pub player_x: i32,
                /// Player's current Y position.
                pub player_y: i32,
                /// Player's current health.
                pub player_health: u32,
                /// Player's maximum health.
                pub player_max_health: u32,
                /// Player's attack stat.
                pub player_attack: u32,
                /// Player's defense stat.
                pub player_defense: u32,
                /// Player's current level.
                pub player_level: u32,
                /// Player's experience points.
                pub player_exp: u32,
                /// Number of enemies defeated.
                pub enemies_defeated: u32,
                /// Whether the boss has been defeated.
                pub boss_defeated: bool,
                /// Current dungeon/area name.
                pub current_area: _rt::String,
                /// Turn counter.
                pub turn_number: u32,
            }
            impl ::core::fmt::Debug for GameState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("GameState")
                        .field("phase", &self.phase)
                        .field("player-x", &self.player_x)
                        .field("player-y", &self.player_y)
                        .field("player-health", &self.player_health)
                        .field("player-max-health", &self.player_max_health)
                        .field("player-attack", &self.player_attack)
                        .field("player-defense", &self.player_defense)
                        .field("player-level", &self.player_level)
                        .field("player-exp", &self.player_exp)
                        .field("enemies-defeated", &self.enemies_defeated)
                        .field("boss-defeated", &self.boss_defeated)
                        .field("current-area", &self.current_area)
                        .field("turn-number", &self.turn_number)
                        .finish()
                }
            }
            /// Tile types in the game world.
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum TileType {
                /// Walkable grass.
                Grass,
                /// Impassable wall.
                Wall,
                /// Walkable water (with items).
                Water,
                /// Forest tile (slower movement).
                Forest,
                /// Dungeon entrance.
                DungeonEntrance,
                /// Shop location.
                Shop,
                /// Treasure chest.
                Chest,
                /// NPC location.
                Npc,
            }
            impl ::core::fmt::Debug for TileType {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        TileType::Grass => f.debug_tuple("TileType::Grass").finish(),
                        TileType::Wall => f.debug_tuple("TileType::Wall").finish(),
                        TileType::Water => f.debug_tuple("TileType::Water").finish(),
                        TileType::Forest => f.debug_tuple("TileType::Forest").finish(),
                        TileType::DungeonEntrance => {
                            f.debug_tuple("TileType::DungeonEntrance").finish()
                        }
                        TileType::Shop => f.debug_tuple("TileType::Shop").finish(),
                        TileType::Chest => f.debug_tuple("TileType::Chest").finish(),
                        TileType::Npc => f.debug_tuple("TileType::Npc").finish(),
                    }
                }
            }
            impl TileType {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> TileType {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => TileType::Grass,
                        1 => TileType::Wall,
                        2 => TileType::Water,
                        3 => TileType::Forest,
                        4 => TileType::DungeonEntrance,
                        5 => TileType::Shop,
                        6 => TileType::Chest,
                        7 => TileType::Npc,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
        }
        /// Game initialization interface.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod init {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type GameState = super::super::super::docs::game_engine::types::GameState;
            #[allow(unused_unsafe, clippy::all)]
            /// Create a new game with default starting state.
            pub fn new_game() -> GameState {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 40 + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 40
                            + 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/init@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "new-game"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                    let l3 = *ptr0.add(4).cast::<i32>();
                    let l4 = *ptr0.add(8).cast::<i32>();
                    let l5 = *ptr0.add(12).cast::<i32>();
                    let l6 = *ptr0.add(16).cast::<i32>();
                    let l7 = *ptr0.add(20).cast::<i32>();
                    let l8 = *ptr0.add(24).cast::<i32>();
                    let l9 = *ptr0.add(28).cast::<i32>();
                    let l10 = *ptr0.add(32).cast::<i32>();
                    let l11 = *ptr0.add(36).cast::<i32>();
                    let l12 = i32::from(*ptr0.add(40).cast::<u8>());
                    let l13 = *ptr0
                        .add(40 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l14 = *ptr0
                        .add(40 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len15 = l14;
                    let bytes15 = _rt::Vec::from_raw_parts(l13.cast(), len15, len15);
                    let l16 = *ptr0
                        .add(40 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>();
                    let result17 = super::super::super::docs::game_engine::types::GameState {
                        phase: super::super::super::docs::game_engine::types::GamePhase::_lift(
                            l2 as u8,
                        ),
                        player_x: l3,
                        player_y: l4,
                        player_health: l5 as u32,
                        player_max_health: l6 as u32,
                        player_attack: l7 as u32,
                        player_defense: l8 as u32,
                        player_level: l9 as u32,
                        player_exp: l10 as u32,
                        enemies_defeated: l11 as u32,
                        boss_defeated: _rt::bool_lift(l12 as u8),
                        current_area: _rt::string_lift(bytes15),
                        turn_number: l16 as u32,
                    };
                    result17
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Load game state (simplified - just validates).
            pub fn validate_state(state: &GameState) -> bool {
                unsafe {
                    let super::super::super::docs::game_engine::types::GameState {
                        phase: phase0,
                        player_x: player_x0,
                        player_y: player_y0,
                        player_health: player_health0,
                        player_max_health: player_max_health0,
                        player_attack: player_attack0,
                        player_defense: player_defense0,
                        player_level: player_level0,
                        player_exp: player_exp0,
                        enemies_defeated: enemies_defeated0,
                        boss_defeated: boss_defeated0,
                        current_area: current_area0,
                        turn_number: turn_number0,
                    } = state;
                    let vec1 = current_area0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/init@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "validate-state"]
                        fn wit_import2(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import2(
                            phase0.clone() as i32,
                            _rt::as_i32(player_x0),
                            _rt::as_i32(player_y0),
                            _rt::as_i32(player_health0),
                            _rt::as_i32(player_max_health0),
                            _rt::as_i32(player_attack0),
                            _rt::as_i32(player_defense0),
                            _rt::as_i32(player_level0),
                            _rt::as_i32(player_exp0),
                            _rt::as_i32(enemies_defeated0),
                            match boss_defeated0 {
                                true => 1,
                                false => 0,
                            },
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_i32(turn_number0),
                        )
                    };
                    _rt::bool_lift(ret as u8)
                }
            }
        }
        /// Game loop and action processing interface.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod engine {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type GameAction = super::super::super::docs::game_engine::types::GameAction;
            pub type ActionResult = super::super::super::docs::game_engine::types::ActionResult;
            pub type GameState = super::super::super::docs::game_engine::types::GameState;
            #[allow(unused_unsafe, clippy::all)]
            /// Process a player action and return the result.
            pub fn process_action(
                state: &GameState,
                action: GameAction,
            ) -> ActionResult {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 4 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 4
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let super::super::super::docs::game_engine::types::GameState {
                        phase: phase0,
                        player_x: player_x0,
                        player_y: player_y0,
                        player_health: player_health0,
                        player_max_health: player_max_health0,
                        player_attack: player_attack0,
                        player_defense: player_defense0,
                        player_level: player_level0,
                        player_exp: player_exp0,
                        enemies_defeated: enemies_defeated0,
                        boss_defeated: boss_defeated0,
                        current_area: current_area0,
                        turn_number: turn_number0,
                    } = state;
                    let vec1 = current_area0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/engine@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "process-action"]
                        fn wit_import3(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(
                            phase0.clone() as i32,
                            _rt::as_i32(player_x0),
                            _rt::as_i32(player_y0),
                            _rt::as_i32(player_health0),
                            _rt::as_i32(player_max_health0),
                            _rt::as_i32(player_attack0),
                            _rt::as_i32(player_defense0),
                            _rt::as_i32(player_level0),
                            _rt::as_i32(player_exp0),
                            _rt::as_i32(enemies_defeated0),
                            match boss_defeated0 {
                                true => 1,
                                false => 0,
                            },
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_i32(turn_number0),
                            action.clone() as i32,
                            ptr2,
                        )
                    };
                    let l4 = i32::from(*ptr2.add(0).cast::<u8>());
                    let l5 = *ptr2
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l6 = *ptr2
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len7 = l6;
                    let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
                    let l8 = i32::from(
                        *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l9 = i32::from(
                        *ptr2
                            .add(1 + 3 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let result10 = super::super::super::docs::game_engine::types::ActionResult {
                        success: _rt::bool_lift(l4 as u8),
                        message: _rt::string_lift(bytes7),
                        new_phase: super::super::super::docs::game_engine::types::GamePhase::_lift(
                            l8 as u8,
                        ),
                        game_continues: _rt::bool_lift(l9 as u8),
                    };
                    result10
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get the current game state as a formatted string.
            pub fn get_status(state: &GameState) -> _rt::String {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let super::super::super::docs::game_engine::types::GameState {
                        phase: phase0,
                        player_x: player_x0,
                        player_y: player_y0,
                        player_health: player_health0,
                        player_max_health: player_max_health0,
                        player_attack: player_attack0,
                        player_defense: player_defense0,
                        player_level: player_level0,
                        player_exp: player_exp0,
                        enemies_defeated: enemies_defeated0,
                        boss_defeated: boss_defeated0,
                        current_area: current_area0,
                        turn_number: turn_number0,
                    } = state;
                    let vec1 = current_area0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/engine@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "get-status"]
                        fn wit_import3(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(
                            phase0.clone() as i32,
                            _rt::as_i32(player_x0),
                            _rt::as_i32(player_y0),
                            _rt::as_i32(player_health0),
                            _rt::as_i32(player_max_health0),
                            _rt::as_i32(player_attack0),
                            _rt::as_i32(player_defense0),
                            _rt::as_i32(player_level0),
                            _rt::as_i32(player_exp0),
                            _rt::as_i32(enemies_defeated0),
                            match boss_defeated0 {
                                true => 1,
                                false => 0,
                            },
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_i32(turn_number0),
                            ptr2,
                        )
                    };
                    let l4 = *ptr2.add(0).cast::<*mut u8>();
                    let l5 = *ptr2
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len6 = l5;
                    let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                    let result7 = _rt::string_lift(bytes6);
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Check for enemy encounters after movement.
            pub fn check_encounter(state: &GameState) -> bool {
                unsafe {
                    let super::super::super::docs::game_engine::types::GameState {
                        phase: phase0,
                        player_x: player_x0,
                        player_y: player_y0,
                        player_health: player_health0,
                        player_max_health: player_max_health0,
                        player_attack: player_attack0,
                        player_defense: player_defense0,
                        player_level: player_level0,
                        player_exp: player_exp0,
                        enemies_defeated: enemies_defeated0,
                        boss_defeated: boss_defeated0,
                        current_area: current_area0,
                        turn_number: turn_number0,
                    } = state;
                    let vec1 = current_area0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/engine@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "check-encounter"]
                        fn wit_import2(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import2(
                            phase0.clone() as i32,
                            _rt::as_i32(player_x0),
                            _rt::as_i32(player_y0),
                            _rt::as_i32(player_health0),
                            _rt::as_i32(player_max_health0),
                            _rt::as_i32(player_attack0),
                            _rt::as_i32(player_defense0),
                            _rt::as_i32(player_level0),
                            _rt::as_i32(player_exp0),
                            _rt::as_i32(enemies_defeated0),
                            match boss_defeated0 {
                                true => 1,
                                false => 0,
                            },
                            ptr1.cast_mut(),
                            len1,
                            _rt::as_i32(turn_number0),
                        )
                    };
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get help text for available actions.
            pub fn get_help() -> _rt::String {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/engine@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "get-help"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = *ptr0.add(0).cast::<*mut u8>();
                    let l3 = *ptr0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len4 = l3;
                    let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                    let result5 = _rt::string_lift(bytes4);
                    result5
                }
            }
        }
        /// World and map interface.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod game_world {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type TileType = super::super::super::docs::game_engine::types::TileType;
            #[allow(unused_unsafe, clippy::all)]
            /// Get the tile type at a position.
            pub fn get_tile(x: i32, y: i32) -> TileType {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/game-world@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "get-tile"]
                        fn wit_import0(_: i32, _: i32) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: i32, _: i32) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0(_rt::as_i32(&x), _rt::as_i32(&y)) };
                    super::super::super::docs::game_engine::types::TileType::_lift(
                        ret as u8,
                    )
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Check if a position is walkable.
            pub fn is_walkable(x: i32, y: i32) -> bool {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/game-world@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "is-walkable"]
                        fn wit_import0(_: i32, _: i32) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: i32, _: i32) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0(_rt::as_i32(&x), _rt::as_i32(&y)) };
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get the name of the current area.
            pub fn get_area_name(x: i32, y: i32) -> _rt::String {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/game-world@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "get-area-name"]
                        fn wit_import1(_: i32, _: i32, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i32, _: i32, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(_rt::as_i32(&x), _rt::as_i32(&y), ptr0) };
                    let l2 = *ptr0.add(0).cast::<*mut u8>();
                    let l3 = *ptr0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len4 = l3;
                    let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                    let result5 = _rt::string_lift(bytes4);
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Check if position has a special event.
            pub fn has_event(x: i32, y: i32) -> bool {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "docs:game-engine/game-world@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "has-event"]
                        fn wit_import0(_: i32, _: i32) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0(_: i32, _: i32) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0(_rt::as_i32(&x), _rt::as_i32(&y)) };
                    _rt::bool_lift(ret as u8)
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:docs:game-engine@0.1.0:app:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1327] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb5\x09\x01A\x02\x01\
A\x0d\x01B\x0a\x01m\x0a\x0amove-north\x0amove-south\x09move-east\x09move-west\x06\
attack\x08use-item\x0eopen-inventory\x08interact\x04wait\x04quit\x04\0\x0bgame-a\
ction\x03\0\0\x01m\x07\x0bexploration\x06combat\x09inventory\x08dialogue\x06paus\
ed\x09game-over\x07victory\x04\0\x0agame-phase\x03\0\x02\x01r\x04\x07success\x7f\
\x07messages\x09new-phase\x03\x0egame-continues\x7f\x04\0\x0daction-result\x03\0\
\x04\x01r\x0d\x05phase\x03\x08player-xz\x08player-yz\x0dplayer-healthy\x11player\
-max-healthy\x0dplayer-attacky\x0eplayer-defensey\x0cplayer-levely\x0aplayer-exp\
y\x10enemies-defeatedy\x0dboss-defeated\x7f\x0ccurrent-areas\x0bturn-numbery\x04\
\0\x0agame-state\x03\0\x06\x01m\x08\x05grass\x04wall\x05water\x06forest\x10dunge\
on-entrance\x04shop\x05chest\x03npc\x04\0\x09tile-type\x03\0\x08\x03\0\x1cdocs:g\
ame-engine/types@0.1.0\x05\0\x02\x03\0\0\x0agame-state\x01B\x06\x02\x03\x02\x01\x01\
\x04\0\x0agame-state\x03\0\0\x01@\0\0\x01\x04\0\x08new-game\x01\x02\x01@\x01\x05\
state\x01\0\x7f\x04\0\x0evalidate-state\x01\x03\x03\0\x1bdocs:game-engine/init@0\
.1.0\x05\x02\x02\x03\0\0\x0bgame-action\x02\x03\0\0\x0daction-result\x02\x03\0\0\
\x0agame-phase\x01B\x10\x02\x03\x02\x01\x03\x04\0\x0bgame-action\x03\0\0\x02\x03\
\x02\x01\x04\x04\0\x0daction-result\x03\0\x02\x02\x03\x02\x01\x01\x04\0\x0agame-\
state\x03\0\x04\x02\x03\x02\x01\x05\x04\0\x0agame-phase\x03\0\x06\x01@\x02\x05st\
ate\x05\x06action\x01\0\x03\x04\0\x0eprocess-action\x01\x08\x01@\x01\x05state\x05\
\0s\x04\0\x0aget-status\x01\x09\x01@\x01\x05state\x05\0\x7f\x04\0\x0fcheck-encou\
nter\x01\x0a\x01@\0\0s\x04\0\x08get-help\x01\x0b\x03\0\x1ddocs:game-engine/engin\
e@0.1.0\x05\x06\x02\x03\0\0\x09tile-type\x01B\x0b\x02\x03\x02\x01\x07\x04\0\x09t\
ile-type\x03\0\0\x02\x03\x02\x01\x01\x04\0\x0agame-state\x03\0\x02\x01@\x02\x01x\
z\x01yz\0\x01\x04\0\x08get-tile\x01\x04\x01@\x02\x01xz\x01yz\0\x7f\x04\0\x0bis-w\
alkable\x01\x05\x01@\x02\x01xz\x01yz\0s\x04\0\x0dget-area-name\x01\x06\x04\0\x09\
has-event\x01\x05\x03\0!docs:game-engine/game-world@0.1.0\x05\x08\x04\0\x1adocs:\
game-engine/app@0.1.0\x04\0\x0b\x09\x01\0\x03app\x03\0\0\0G\x09producers\x01\x0c\
processed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
