// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod docs {
        pub mod enemy {
            /// Enemy type definitions and data structures.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                /// Types of enemies in the game.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum EnemyKind {
                    /// Basic slime enemy - slow, low damage.
                    Slime,
                    /// Skeleton warrior - medium speed, uses sword.
                    Skeleton,
                    /// Bat - fast, flies over obstacles.
                    Bat,
                    /// Goblin - aggressive, medium stats.
                    Goblin,
                    /// Dark knight - heavy armor, high damage.
                    DarkKnight,
                    /// Boss - powerful, unique attack patterns.
                    Boss,
                }
                impl ::core::fmt::Debug for EnemyKind {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            EnemyKind::Slime => {
                                f.debug_tuple("EnemyKind::Slime").finish()
                            }
                            EnemyKind::Skeleton => {
                                f.debug_tuple("EnemyKind::Skeleton").finish()
                            }
                            EnemyKind::Bat => f.debug_tuple("EnemyKind::Bat").finish(),
                            EnemyKind::Goblin => {
                                f.debug_tuple("EnemyKind::Goblin").finish()
                            }
                            EnemyKind::DarkKnight => {
                                f.debug_tuple("EnemyKind::DarkKnight").finish()
                            }
                            EnemyKind::Boss => f.debug_tuple("EnemyKind::Boss").finish(),
                        }
                    }
                }
                impl EnemyKind {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> EnemyKind {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => EnemyKind::Slime,
                            1 => EnemyKind::Skeleton,
                            2 => EnemyKind::Bat,
                            3 => EnemyKind::Goblin,
                            4 => EnemyKind::DarkKnight,
                            5 => EnemyKind::Boss,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// AI behavior patterns for enemies.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Behavior {
                    /// Wanders randomly, attacks when player is close.
                    Wander,
                    /// Actively chases the player.
                    Chase,
                    /// Stays in place, attacks nearby players.
                    Guard,
                    /// Runs away when health is low.
                    Flee,
                    /// Complex boss-specific attack patterns.
                    BossPattern,
                }
                impl ::core::fmt::Debug for Behavior {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Behavior::Wander => {
                                f.debug_tuple("Behavior::Wander").finish()
                            }
                            Behavior::Chase => f.debug_tuple("Behavior::Chase").finish(),
                            Behavior::Guard => f.debug_tuple("Behavior::Guard").finish(),
                            Behavior::Flee => f.debug_tuple("Behavior::Flee").finish(),
                            Behavior::BossPattern => {
                                f.debug_tuple("Behavior::BossPattern").finish()
                            }
                        }
                    }
                }
                impl Behavior {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Behavior {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Behavior::Wander,
                            1 => Behavior::Chase,
                            2 => Behavior::Guard,
                            3 => Behavior::Flee,
                            4 => Behavior::BossPattern,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Enemy position in 2D world coordinates.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Position {
                    /// X coordinate (horizontal position).
                    pub x: i32,
                    /// Y coordinate (vertical position).
                    pub y: i32,
                }
                impl ::core::fmt::Debug for Position {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Position")
                            .field("x", &self.x)
                            .field("y", &self.y)
                            .finish()
                    }
                }
                /// Complete enemy state.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct EnemyState {
                    /// Type of enemy.
                    pub kind: EnemyKind,
                    /// Current health points.
                    pub health: u32,
                    /// Maximum health points.
                    pub max_health: u32,
                    /// Attack damage dealt to player.
                    pub attack: u32,
                    /// Defense rating for damage reduction.
                    pub defense: u32,
                    /// Experience reward when defeated.
                    pub exp_reward: u32,
                    /// Current position in the world.
                    pub pos: Position,
                    /// Current AI behavior.
                    pub current_behavior: Behavior,
                    /// Whether the enemy is currently alive.
                    pub is_alive: bool,
                }
                impl ::core::fmt::Debug for EnemyState {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("EnemyState")
                            .field("kind", &self.kind)
                            .field("health", &self.health)
                            .field("max-health", &self.max_health)
                            .field("attack", &self.attack)
                            .field("defense", &self.defense)
                            .field("exp-reward", &self.exp_reward)
                            .field("pos", &self.pos)
                            .field("current-behavior", &self.current_behavior)
                            .field("is-alive", &self.is_alive)
                            .finish()
                    }
                }
                #[doc(hidden)]
                macro_rules! __export_docs_enemy_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_enemy_types_0_1_0_cabi;
            }
            /// Enemy spawning and creation interface.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod spawn {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type EnemyKind = super::super::super::super::exports::docs::enemy::types::EnemyKind;
                pub type EnemyState = super::super::super::super::exports::docs::enemy::types::EnemyState;
                pub type Position = super::super::super::super::exports::docs::enemy::types::Position;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_spawn_enemy_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::spawn_enemy(
                        super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                            arg0 as u8,
                        ),
                        super::super::super::super::exports::docs::enemy::types::Position {
                            x: arg1,
                            y: arg2,
                        },
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: kind2,
                        health: health2,
                        max_health: max_health2,
                        attack: attack2,
                        defense: defense2,
                        exp_reward: exp_reward2,
                        pos: pos2,
                        current_behavior: current_behavior2,
                        is_alive: is_alive2,
                    } = result0;
                    *ptr1.add(0).cast::<u8>() = (kind2.clone() as i32) as u8;
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(health2);
                    *ptr1.add(8).cast::<i32>() = _rt::as_i32(max_health2);
                    *ptr1.add(12).cast::<i32>() = _rt::as_i32(attack2);
                    *ptr1.add(16).cast::<i32>() = _rt::as_i32(defense2);
                    *ptr1.add(20).cast::<i32>() = _rt::as_i32(exp_reward2);
                    let super::super::super::super::exports::docs::enemy::types::Position {
                        x: x3,
                        y: y3,
                    } = pos2;
                    *ptr1.add(24).cast::<i32>() = _rt::as_i32(x3);
                    *ptr1.add(28).cast::<i32>() = _rt::as_i32(y3);
                    *ptr1.add(32).cast::<u8>() = (current_behavior2.clone() as i32)
                        as u8;
                    *ptr1.add(33).cast::<u8>() = (match is_alive2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_spawn_boss_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::spawn_boss(super::super::super::super::exports::docs::enemy::types::Position {
                        x: arg0,
                        y: arg1,
                    });
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: kind2,
                        health: health2,
                        max_health: max_health2,
                        attack: attack2,
                        defense: defense2,
                        exp_reward: exp_reward2,
                        pos: pos2,
                        current_behavior: current_behavior2,
                        is_alive: is_alive2,
                    } = result0;
                    *ptr1.add(0).cast::<u8>() = (kind2.clone() as i32) as u8;
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(health2);
                    *ptr1.add(8).cast::<i32>() = _rt::as_i32(max_health2);
                    *ptr1.add(12).cast::<i32>() = _rt::as_i32(attack2);
                    *ptr1.add(16).cast::<i32>() = _rt::as_i32(defense2);
                    *ptr1.add(20).cast::<i32>() = _rt::as_i32(exp_reward2);
                    let super::super::super::super::exports::docs::enemy::types::Position {
                        x: x3,
                        y: y3,
                    } = pos2;
                    *ptr1.add(24).cast::<i32>() = _rt::as_i32(x3);
                    *ptr1.add(28).cast::<i32>() = _rt::as_i32(y3);
                    *ptr1.add(32).cast::<u8>() = (current_behavior2.clone() as i32)
                        as u8;
                    *ptr1.add(33).cast::<u8>() = (match is_alive2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_base_stats_cabi<T: Guest>(
                    arg0: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_base_stats(
                        super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                            arg0 as u8,
                        ),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: kind2,
                        health: health2,
                        max_health: max_health2,
                        attack: attack2,
                        defense: defense2,
                        exp_reward: exp_reward2,
                        pos: pos2,
                        current_behavior: current_behavior2,
                        is_alive: is_alive2,
                    } = result0;
                    *ptr1.add(0).cast::<u8>() = (kind2.clone() as i32) as u8;
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(health2);
                    *ptr1.add(8).cast::<i32>() = _rt::as_i32(max_health2);
                    *ptr1.add(12).cast::<i32>() = _rt::as_i32(attack2);
                    *ptr1.add(16).cast::<i32>() = _rt::as_i32(defense2);
                    *ptr1.add(20).cast::<i32>() = _rt::as_i32(exp_reward2);
                    let super::super::super::super::exports::docs::enemy::types::Position {
                        x: x3,
                        y: y3,
                    } = pos2;
                    *ptr1.add(24).cast::<i32>() = _rt::as_i32(x3);
                    *ptr1.add(28).cast::<i32>() = _rt::as_i32(y3);
                    *ptr1.add(32).cast::<u8>() = (current_behavior2.clone() as i32)
                        as u8;
                    *ptr1.add(33).cast::<u8>() = (match is_alive2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    ptr1
                }
                pub trait Guest {
                    /// Spawn a new enemy of the specified kind at the given position.
                    fn spawn_enemy(kind: EnemyKind, pos: Position) -> EnemyState;
                    /// Spawn a boss enemy with enhanced stats.
                    fn spawn_boss(pos: Position) -> EnemyState;
                    /// Get the base stats for an enemy kind.
                    fn get_base_stats(kind: EnemyKind) -> EnemyState;
                }
                #[doc(hidden)]
                macro_rules! __export_docs_enemy_spawn_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "docs:enemy/spawn@0.1.0#spawn-enemy")] unsafe extern "C" fn
                        export_spawn_enemy(arg0 : i32, arg1 : i32, arg2 : i32,) -> * mut
                        u8 { unsafe { $($path_to_types)*:: _export_spawn_enemy_cabi::<$ty
                        > (arg0, arg1, arg2) } } #[unsafe (export_name =
                        "docs:enemy/spawn@0.1.0#spawn-boss")] unsafe extern "C" fn
                        export_spawn_boss(arg0 : i32, arg1 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_spawn_boss_cabi::<$ty > (arg0, arg1)
                        } } #[unsafe (export_name =
                        "docs:enemy/spawn@0.1.0#get-base-stats")] unsafe extern "C" fn
                        export_get_base_stats(arg0 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_base_stats_cabi::<$ty > (arg0) }
                        } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_enemy_spawn_0_1_0_cabi;
                #[repr(align(4))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 36]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 36],
                );
            }
            /// Enemy AI and behavior interface.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod ai {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type EnemyState = super::super::super::super::exports::docs::enemy::types::EnemyState;
                pub type Position = super::super::super::super::exports::docs::enemy::types::Position;
                pub type Behavior = super::super::super::super::exports::docs::enemy::types::Behavior;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_calculate_move_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                    arg11: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::calculate_move(
                        super::super::super::super::exports::docs::enemy::types::EnemyState {
                            kind: super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                                arg0 as u8,
                            ),
                            health: arg1 as u32,
                            max_health: arg2 as u32,
                            attack: arg3 as u32,
                            defense: arg4 as u32,
                            exp_reward: arg5 as u32,
                            pos: super::super::super::super::exports::docs::enemy::types::Position {
                                x: arg6,
                                y: arg7,
                            },
                            current_behavior: super::super::super::super::exports::docs::enemy::types::Behavior::_lift(
                                arg8 as u8,
                            ),
                            is_alive: _rt::bool_lift(arg9 as u8),
                        },
                        super::super::super::super::exports::docs::enemy::types::Position {
                            x: arg10,
                            y: arg11,
                        },
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::exports::docs::enemy::types::Position {
                        x: x2,
                        y: y2,
                    } = result0;
                    *ptr1.add(0).cast::<i32>() = _rt::as_i32(x2);
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(y2);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_should_attack_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                    arg11: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::should_attack(
                        super::super::super::super::exports::docs::enemy::types::EnemyState {
                            kind: super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                                arg0 as u8,
                            ),
                            health: arg1 as u32,
                            max_health: arg2 as u32,
                            attack: arg3 as u32,
                            defense: arg4 as u32,
                            exp_reward: arg5 as u32,
                            pos: super::super::super::super::exports::docs::enemy::types::Position {
                                x: arg6,
                                y: arg7,
                            },
                            current_behavior: super::super::super::super::exports::docs::enemy::types::Behavior::_lift(
                                arg8 as u8,
                            ),
                            is_alive: _rt::bool_lift(arg9 as u8),
                        },
                        super::super::super::super::exports::docs::enemy::types::Position {
                            x: arg10,
                            y: arg11,
                        },
                    );
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_update_behavior_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::update_behavior(super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                            arg0 as u8,
                        ),
                        health: arg1 as u32,
                        max_health: arg2 as u32,
                        attack: arg3 as u32,
                        defense: arg4 as u32,
                        exp_reward: arg5 as u32,
                        pos: super::super::super::super::exports::docs::enemy::types::Position {
                            x: arg6,
                            y: arg7,
                        },
                        current_behavior: super::super::super::super::exports::docs::enemy::types::Behavior::_lift(
                            arg8 as u8,
                        ),
                        is_alive: _rt::bool_lift(arg9 as u8),
                    });
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_attack_damage_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_attack_damage(super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                            arg0 as u8,
                        ),
                        health: arg1 as u32,
                        max_health: arg2 as u32,
                        attack: arg3 as u32,
                        defense: arg4 as u32,
                        exp_reward: arg5 as u32,
                        pos: super::super::super::super::exports::docs::enemy::types::Position {
                            x: arg6,
                            y: arg7,
                        },
                        current_behavior: super::super::super::super::exports::docs::enemy::types::Behavior::_lift(
                            arg8 as u8,
                        ),
                        is_alive: _rt::bool_lift(arg9 as u8),
                    });
                    _rt::as_i32(result0)
                }
                pub trait Guest {
                    /// Calculate the enemy's next move based on player position.
                    ///
                    /// Returns the new position the enemy wants to move to.
                    fn calculate_move(
                        enemy: EnemyState,
                        player_pos: Position,
                    ) -> Position;
                    /// Determine if the enemy should attack based on distance.
                    fn should_attack(enemy: EnemyState, player_pos: Position) -> bool;
                    /// Update the enemy's behavior based on its current state.
                    fn update_behavior(enemy: EnemyState) -> Behavior;
                    /// Calculate attack damage this enemy will deal.
                    fn get_attack_damage(enemy: EnemyState) -> u32;
                }
                #[doc(hidden)]
                macro_rules! __export_docs_enemy_ai_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "docs:enemy/ai@0.1.0#calculate-move")] unsafe extern "C" fn
                        export_calculate_move(arg0 : i32, arg1 : i32, arg2 : i32, arg3 :
                        i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 : i32,
                        arg9 : i32, arg10 : i32, arg11 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_calculate_move_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                        arg11) } } #[unsafe (export_name =
                        "docs:enemy/ai@0.1.0#should-attack")] unsafe extern "C" fn
                        export_should_attack(arg0 : i32, arg1 : i32, arg2 : i32, arg3 :
                        i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 : i32,
                        arg9 : i32, arg10 : i32, arg11 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_should_attack_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                        arg11) } } #[unsafe (export_name =
                        "docs:enemy/ai@0.1.0#update-behavior")] unsafe extern "C" fn
                        export_update_behavior(arg0 : i32, arg1 : i32, arg2 : i32, arg3 :
                        i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 : i32,
                        arg9 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_update_behavior_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9) } } #[unsafe (export_name =
                        "docs:enemy/ai@0.1.0#get-attack-damage")] unsafe extern "C" fn
                        export_get_attack_damage(arg0 : i32, arg1 : i32, arg2 : i32, arg3
                        : i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 :
                        i32, arg9 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_get_attack_damage_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_enemy_ai_0_1_0_cabi;
                #[repr(align(4))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 8]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8],
                );
            }
            /// Enemy damage and health interface.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod damage {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type EnemyState = super::super::super::super::exports::docs::enemy::types::EnemyState;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_take_damage_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::take_damage(
                        super::super::super::super::exports::docs::enemy::types::EnemyState {
                            kind: super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                                arg0 as u8,
                            ),
                            health: arg1 as u32,
                            max_health: arg2 as u32,
                            attack: arg3 as u32,
                            defense: arg4 as u32,
                            exp_reward: arg5 as u32,
                            pos: super::super::super::super::exports::docs::enemy::types::Position {
                                x: arg6,
                                y: arg7,
                            },
                            current_behavior: super::super::super::super::exports::docs::enemy::types::Behavior::_lift(
                                arg8 as u8,
                            ),
                            is_alive: _rt::bool_lift(arg9 as u8),
                        },
                        arg10 as u32,
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: kind2,
                        health: health2,
                        max_health: max_health2,
                        attack: attack2,
                        defense: defense2,
                        exp_reward: exp_reward2,
                        pos: pos2,
                        current_behavior: current_behavior2,
                        is_alive: is_alive2,
                    } = result0;
                    *ptr1.add(0).cast::<u8>() = (kind2.clone() as i32) as u8;
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(health2);
                    *ptr1.add(8).cast::<i32>() = _rt::as_i32(max_health2);
                    *ptr1.add(12).cast::<i32>() = _rt::as_i32(attack2);
                    *ptr1.add(16).cast::<i32>() = _rt::as_i32(defense2);
                    *ptr1.add(20).cast::<i32>() = _rt::as_i32(exp_reward2);
                    let super::super::super::super::exports::docs::enemy::types::Position {
                        x: x3,
                        y: y3,
                    } = pos2;
                    *ptr1.add(24).cast::<i32>() = _rt::as_i32(x3);
                    *ptr1.add(28).cast::<i32>() = _rt::as_i32(y3);
                    *ptr1.add(32).cast::<u8>() = (current_behavior2.clone() as i32)
                        as u8;
                    *ptr1.add(33).cast::<u8>() = (match is_alive2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_defeated_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::is_defeated(super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                            arg0 as u8,
                        ),
                        health: arg1 as u32,
                        max_health: arg2 as u32,
                        attack: arg3 as u32,
                        defense: arg4 as u32,
                        exp_reward: arg5 as u32,
                        pos: super::super::super::super::exports::docs::enemy::types::Position {
                            x: arg6,
                            y: arg7,
                        },
                        current_behavior: super::super::super::super::exports::docs::enemy::types::Behavior::_lift(
                            arg8 as u8,
                        ),
                        is_alive: _rt::bool_lift(arg9 as u8),
                    });
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_exp_reward_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_exp_reward(super::super::super::super::exports::docs::enemy::types::EnemyState {
                        kind: super::super::super::super::exports::docs::enemy::types::EnemyKind::_lift(
                            arg0 as u8,
                        ),
                        health: arg1 as u32,
                        max_health: arg2 as u32,
                        attack: arg3 as u32,
                        defense: arg4 as u32,
                        exp_reward: arg5 as u32,
                        pos: super::super::super::super::exports::docs::enemy::types::Position {
                            x: arg6,
                            y: arg7,
                        },
                        current_behavior: super::super::super::super::exports::docs::enemy::types::Behavior::_lift(
                            arg8 as u8,
                        ),
                        is_alive: _rt::bool_lift(arg9 as u8),
                    });
                    _rt::as_i32(result0)
                }
                pub trait Guest {
                    /// Apply damage to an enemy.
                    ///
                    /// Returns updated enemy state after damage calculation.
                    fn take_damage(enemy: EnemyState, raw_damage: u32) -> EnemyState;
                    /// Check if the enemy is defeated.
                    fn is_defeated(enemy: EnemyState) -> bool;
                    /// Get the experience reward for defeating this enemy.
                    fn get_exp_reward(enemy: EnemyState) -> u32;
                }
                #[doc(hidden)]
                macro_rules! __export_docs_enemy_damage_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "docs:enemy/damage@0.1.0#take-damage")] unsafe extern "C" fn
                        export_take_damage(arg0 : i32, arg1 : i32, arg2 : i32, arg3 :
                        i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 : i32,
                        arg9 : i32, arg10 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_take_damage_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) } }
                        #[unsafe (export_name = "docs:enemy/damage@0.1.0#is-defeated")]
                        unsafe extern "C" fn export_is_defeated(arg0 : i32, arg1 : i32,
                        arg2 : i32, arg3 : i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7
                        : i32, arg8 : i32, arg9 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_is_defeated_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) } }
                        #[unsafe (export_name =
                        "docs:enemy/damage@0.1.0#get-exp-reward")] unsafe extern "C" fn
                        export_get_exp_reward(arg0 : i32, arg1 : i32, arg2 : i32, arg3 :
                        i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 : i32,
                        arg9 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_get_exp_reward_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_enemy_damage_0_1_0_cabi;
                #[repr(align(4))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 36]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 36],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_enemy_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::docs::enemy::types::__export_docs_enemy_types_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::enemy::types);
        $($path_to_types_root)*::
        exports::docs::enemy::spawn::__export_docs_enemy_spawn_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::enemy::spawn);
        $($path_to_types_root)*::
        exports::docs::enemy::ai::__export_docs_enemy_ai_0_1_0_cabi!($ty with_types_in
        $($path_to_types_root)*:: exports::docs::enemy::ai); $($path_to_types_root)*::
        exports::docs::enemy::damage::__export_docs_enemy_damage_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::enemy::damage);
    };
}
#[doc(inline)]
pub(crate) use __export_enemy_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:docs:enemy@0.1.0:enemy:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1060] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa8\x07\x01A\x02\x01\
A\x0c\x01B\x08\x01m\x06\x05slime\x08skeleton\x03bat\x06goblin\x0bdark-knight\x04\
boss\x04\0\x0aenemy-kind\x03\0\0\x01m\x05\x06wander\x05chase\x05guard\x04flee\x0c\
boss-pattern\x04\0\x08behavior\x03\0\x02\x01r\x02\x01xz\x01yz\x04\0\x08position\x03\
\0\x04\x01r\x09\x04kind\x01\x06healthy\x0amax-healthy\x06attacky\x07defensey\x0a\
exp-rewardy\x03pos\x05\x10current-behavior\x03\x08is-alive\x7f\x04\0\x0benemy-st\
ate\x03\0\x06\x04\0\x16docs:enemy/types@0.1.0\x05\0\x02\x03\0\0\x0aenemy-kind\x02\
\x03\0\0\x0benemy-state\x02\x03\0\0\x08position\x01B\x0c\x02\x03\x02\x01\x01\x04\
\0\x0aenemy-kind\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0benemy-state\x03\0\x02\x02\x03\
\x02\x01\x03\x04\0\x08position\x03\0\x04\x01@\x02\x04kind\x01\x03pos\x05\0\x03\x04\
\0\x0bspawn-enemy\x01\x06\x01@\x01\x03pos\x05\0\x03\x04\0\x0aspawn-boss\x01\x07\x01\
@\x01\x04kind\x01\0\x03\x04\0\x0eget-base-stats\x01\x08\x04\0\x16docs:enemy/spaw\
n@0.1.0\x05\x04\x02\x03\0\0\x08behavior\x01B\x0e\x02\x03\x02\x01\x02\x04\0\x0ben\
emy-state\x03\0\0\x02\x03\x02\x01\x03\x04\0\x08position\x03\0\x02\x02\x03\x02\x01\
\x05\x04\0\x08behavior\x03\0\x04\x01@\x02\x05enemy\x01\x0aplayer-pos\x03\0\x03\x04\
\0\x0ecalculate-move\x01\x06\x01@\x02\x05enemy\x01\x0aplayer-pos\x03\0\x7f\x04\0\
\x0dshould-attack\x01\x07\x01@\x01\x05enemy\x01\0\x05\x04\0\x0fupdate-behavior\x01\
\x08\x01@\x01\x05enemy\x01\0y\x04\0\x11get-attack-damage\x01\x09\x04\0\x13docs:e\
nemy/ai@0.1.0\x05\x06\x01B\x08\x02\x03\x02\x01\x02\x04\0\x0benemy-state\x03\0\0\x01\
@\x02\x05enemy\x01\x0araw-damagey\0\x01\x04\0\x0btake-damage\x01\x02\x01@\x01\x05\
enemy\x01\0\x7f\x04\0\x0bis-defeated\x01\x03\x01@\x01\x05enemy\x01\0y\x04\0\x0eg\
et-exp-reward\x01\x04\x04\0\x17docs:enemy/damage@0.1.0\x05\x07\x04\0\x16docs:ene\
my/enemy@0.1.0\x04\0\x0b\x0b\x01\0\x05enemy\x03\0\0\0G\x09producers\x01\x0cproce\
ssed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
