// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod docs {
        pub mod game_engine {
            /// Game state and world definitions.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Game actions the player can perform.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum GameAction {
                    /// Move in a direction.
                    MoveNorth,
                    MoveSouth,
                    MoveEast,
                    MoveWest,
                    /// Attack with current weapon.
                    Attack,
                    /// Use an item from inventory.
                    UseItem,
                    /// Open inventory menu.
                    OpenInventory,
                    /// Interact with environment/NPC.
                    Interact,
                    /// Wait/skip turn.
                    Wait,
                    /// Quit the game.
                    Quit,
                }
                impl ::core::fmt::Debug for GameAction {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            GameAction::MoveNorth => {
                                f.debug_tuple("GameAction::MoveNorth").finish()
                            }
                            GameAction::MoveSouth => {
                                f.debug_tuple("GameAction::MoveSouth").finish()
                            }
                            GameAction::MoveEast => {
                                f.debug_tuple("GameAction::MoveEast").finish()
                            }
                            GameAction::MoveWest => {
                                f.debug_tuple("GameAction::MoveWest").finish()
                            }
                            GameAction::Attack => {
                                f.debug_tuple("GameAction::Attack").finish()
                            }
                            GameAction::UseItem => {
                                f.debug_tuple("GameAction::UseItem").finish()
                            }
                            GameAction::OpenInventory => {
                                f.debug_tuple("GameAction::OpenInventory").finish()
                            }
                            GameAction::Interact => {
                                f.debug_tuple("GameAction::Interact").finish()
                            }
                            GameAction::Wait => {
                                f.debug_tuple("GameAction::Wait").finish()
                            }
                            GameAction::Quit => {
                                f.debug_tuple("GameAction::Quit").finish()
                            }
                        }
                    }
                }
                impl GameAction {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> GameAction {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => GameAction::MoveNorth,
                            1 => GameAction::MoveSouth,
                            2 => GameAction::MoveEast,
                            3 => GameAction::MoveWest,
                            4 => GameAction::Attack,
                            5 => GameAction::UseItem,
                            6 => GameAction::OpenInventory,
                            7 => GameAction::Interact,
                            8 => GameAction::Wait,
                            9 => GameAction::Quit,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Current game phase.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum GamePhase {
                    /// Exploring the world.
                    Exploration,
                    /// In combat with an enemy.
                    Combat,
                    /// Viewing inventory.
                    Inventory,
                    /// Talking to NPC or reading sign.
                    Dialogue,
                    /// Game is paused.
                    Paused,
                    /// Game over (player defeated).
                    GameOver,
                    /// Victory (boss defeated).
                    Victory,
                }
                impl ::core::fmt::Debug for GamePhase {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            GamePhase::Exploration => {
                                f.debug_tuple("GamePhase::Exploration").finish()
                            }
                            GamePhase::Combat => {
                                f.debug_tuple("GamePhase::Combat").finish()
                            }
                            GamePhase::Inventory => {
                                f.debug_tuple("GamePhase::Inventory").finish()
                            }
                            GamePhase::Dialogue => {
                                f.debug_tuple("GamePhase::Dialogue").finish()
                            }
                            GamePhase::Paused => {
                                f.debug_tuple("GamePhase::Paused").finish()
                            }
                            GamePhase::GameOver => {
                                f.debug_tuple("GamePhase::GameOver").finish()
                            }
                            GamePhase::Victory => {
                                f.debug_tuple("GamePhase::Victory").finish()
                            }
                        }
                    }
                }
                impl GamePhase {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> GamePhase {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => GamePhase::Exploration,
                            1 => GamePhase::Combat,
                            2 => GamePhase::Inventory,
                            3 => GamePhase::Dialogue,
                            4 => GamePhase::Paused,
                            5 => GamePhase::GameOver,
                            6 => GamePhase::Victory,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Result of processing a game action.
                #[derive(Clone)]
                pub struct ActionResult {
                    /// Whether the action was successful.
                    pub success: bool,
                    /// Description of what happened.
                    pub message: _rt::String,
                    /// New game phase after action.
                    pub new_phase: GamePhase,
                    /// Whether the game should continue.
                    pub game_continues: bool,
                }
                impl ::core::fmt::Debug for ActionResult {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ActionResult")
                            .field("success", &self.success)
                            .field("message", &self.message)
                            .field("new-phase", &self.new_phase)
                            .field("game-continues", &self.game_continues)
                            .finish()
                    }
                }
                /// Complete game state snapshot.
                #[derive(Clone)]
                pub struct GameState {
                    /// Current game phase.
                    pub phase: GamePhase,
                    /// Player's current X position.
                    pub player_x: i32,
                    /// Player's current Y position.
                    pub player_y: i32,
                    /// Player's current health.
                    pub player_health: u32,
                    /// Player's maximum health.
                    pub player_max_health: u32,
                    /// Player's attack stat.
                    pub player_attack: u32,
                    /// Player's defense stat.
                    pub player_defense: u32,
                    /// Player's current level.
                    pub player_level: u32,
                    /// Player's experience points.
                    pub player_exp: u32,
                    /// Number of enemies defeated.
                    pub enemies_defeated: u32,
                    /// Whether the boss has been defeated.
                    pub boss_defeated: bool,
                    /// Current dungeon/area name.
                    pub current_area: _rt::String,
                    /// Turn counter.
                    pub turn_number: u32,
                }
                impl ::core::fmt::Debug for GameState {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("GameState")
                            .field("phase", &self.phase)
                            .field("player-x", &self.player_x)
                            .field("player-y", &self.player_y)
                            .field("player-health", &self.player_health)
                            .field("player-max-health", &self.player_max_health)
                            .field("player-attack", &self.player_attack)
                            .field("player-defense", &self.player_defense)
                            .field("player-level", &self.player_level)
                            .field("player-exp", &self.player_exp)
                            .field("enemies-defeated", &self.enemies_defeated)
                            .field("boss-defeated", &self.boss_defeated)
                            .field("current-area", &self.current_area)
                            .field("turn-number", &self.turn_number)
                            .finish()
                    }
                }
                /// Tile types in the game world.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum TileType {
                    /// Walkable grass.
                    Grass,
                    /// Impassable wall.
                    Wall,
                    /// Walkable water (with items).
                    Water,
                    /// Forest tile (slower movement).
                    Forest,
                    /// Dungeon entrance.
                    DungeonEntrance,
                    /// Shop location.
                    Shop,
                    /// Treasure chest.
                    Chest,
                    /// NPC location.
                    Npc,
                }
                impl ::core::fmt::Debug for TileType {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            TileType::Grass => f.debug_tuple("TileType::Grass").finish(),
                            TileType::Wall => f.debug_tuple("TileType::Wall").finish(),
                            TileType::Water => f.debug_tuple("TileType::Water").finish(),
                            TileType::Forest => {
                                f.debug_tuple("TileType::Forest").finish()
                            }
                            TileType::DungeonEntrance => {
                                f.debug_tuple("TileType::DungeonEntrance").finish()
                            }
                            TileType::Shop => f.debug_tuple("TileType::Shop").finish(),
                            TileType::Chest => f.debug_tuple("TileType::Chest").finish(),
                            TileType::Npc => f.debug_tuple("TileType::Npc").finish(),
                        }
                    }
                }
                impl TileType {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> TileType {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => TileType::Grass,
                            1 => TileType::Wall,
                            2 => TileType::Water,
                            3 => TileType::Forest,
                            4 => TileType::DungeonEntrance,
                            5 => TileType::Shop,
                            6 => TileType::Chest,
                            7 => TileType::Npc,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[doc(hidden)]
                macro_rules! __export_docs_game_engine_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_game_engine_types_0_1_0_cabi;
            }
            /// Game initialization interface.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod init {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type GameState = super::super::super::super::exports::docs::game_engine::types::GameState;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_new_game_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::new_game();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::exports::docs::game_engine::types::GameState {
                        phase: phase2,
                        player_x: player_x2,
                        player_y: player_y2,
                        player_health: player_health2,
                        player_max_health: player_max_health2,
                        player_attack: player_attack2,
                        player_defense: player_defense2,
                        player_level: player_level2,
                        player_exp: player_exp2,
                        enemies_defeated: enemies_defeated2,
                        boss_defeated: boss_defeated2,
                        current_area: current_area2,
                        turn_number: turn_number2,
                    } = result0;
                    *ptr1.add(0).cast::<u8>() = (phase2.clone() as i32) as u8;
                    *ptr1.add(4).cast::<i32>() = _rt::as_i32(player_x2);
                    *ptr1.add(8).cast::<i32>() = _rt::as_i32(player_y2);
                    *ptr1.add(12).cast::<i32>() = _rt::as_i32(player_health2);
                    *ptr1.add(16).cast::<i32>() = _rt::as_i32(player_max_health2);
                    *ptr1.add(20).cast::<i32>() = _rt::as_i32(player_attack2);
                    *ptr1.add(24).cast::<i32>() = _rt::as_i32(player_defense2);
                    *ptr1.add(28).cast::<i32>() = _rt::as_i32(player_level2);
                    *ptr1.add(32).cast::<i32>() = _rt::as_i32(player_exp2);
                    *ptr1.add(36).cast::<i32>() = _rt::as_i32(enemies_defeated2);
                    *ptr1.add(40).cast::<u8>() = (match boss_defeated2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    let vec3 = (current_area2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1
                        .add(40 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len3;
                    *ptr1
                        .add(40 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr3.cast_mut();
                    *ptr1
                        .add(40 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<i32>() = _rt::as_i32(turn_number2);
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_new_game<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0
                        .add(40 + 1 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l1 = *arg0
                        .add(40 + 2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_state_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                    arg11: *mut u8,
                    arg12: usize,
                    arg13: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg12;
                    let bytes0 = _rt::Vec::from_raw_parts(arg11.cast(), len0, len0);
                    let result1 = T::validate_state(super::super::super::super::exports::docs::game_engine::types::GameState {
                        phase: super::super::super::super::exports::docs::game_engine::types::GamePhase::_lift(
                            arg0 as u8,
                        ),
                        player_x: arg1,
                        player_y: arg2,
                        player_health: arg3 as u32,
                        player_max_health: arg4 as u32,
                        player_attack: arg5 as u32,
                        player_defense: arg6 as u32,
                        player_level: arg7 as u32,
                        player_exp: arg8 as u32,
                        enemies_defeated: arg9 as u32,
                        boss_defeated: _rt::bool_lift(arg10 as u8),
                        current_area: _rt::string_lift(bytes0),
                        turn_number: arg13 as u32,
                    });
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                pub trait Guest {
                    /// Create a new game with default starting state.
                    fn new_game() -> GameState;
                    /// Load game state (simplified - just validates).
                    fn validate_state(state: GameState) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_docs_game_engine_init_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "docs:game-engine/init@0.1.0#new-game")] unsafe extern "C" fn
                        export_new_game() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_new_game_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_docs:game-engine/init@0.1.0#new-game")] unsafe extern
                        "C" fn _post_return_new_game(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_new_game::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "docs:game-engine/init@0.1.0#validate-state")] unsafe extern "C"
                        fn export_validate_state(arg0 : i32, arg1 : i32, arg2 : i32, arg3
                        : i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 :
                        i32, arg9 : i32, arg10 : i32, arg11 : * mut u8, arg12 : usize,
                        arg13 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_validate_state_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) }
                        } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_game_engine_init_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 40 + 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 40
                        + 4 * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Game loop and action processing interface.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod engine {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type GameAction = super::super::super::super::exports::docs::game_engine::types::GameAction;
                pub type ActionResult = super::super::super::super::exports::docs::game_engine::types::ActionResult;
                pub type GameState = super::super::super::super::exports::docs::game_engine::types::GameState;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_process_action_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                    arg11: *mut u8,
                    arg12: usize,
                    arg13: i32,
                    arg14: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg12;
                    let bytes0 = _rt::Vec::from_raw_parts(arg11.cast(), len0, len0);
                    let result1 = T::process_action(
                        super::super::super::super::exports::docs::game_engine::types::GameState {
                            phase: super::super::super::super::exports::docs::game_engine::types::GamePhase::_lift(
                                arg0 as u8,
                            ),
                            player_x: arg1,
                            player_y: arg2,
                            player_health: arg3 as u32,
                            player_max_health: arg4 as u32,
                            player_attack: arg5 as u32,
                            player_defense: arg6 as u32,
                            player_level: arg7 as u32,
                            player_exp: arg8 as u32,
                            enemies_defeated: arg9 as u32,
                            boss_defeated: _rt::bool_lift(arg10 as u8),
                            current_area: _rt::string_lift(bytes0),
                            turn_number: arg13 as u32,
                        },
                        super::super::super::super::exports::docs::game_engine::types::GameAction::_lift(
                            arg14 as u8,
                        ),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::exports::docs::game_engine::types::ActionResult {
                        success: success3,
                        message: message3,
                        new_phase: new_phase3,
                        game_continues: game_continues3,
                    } = result1;
                    *ptr2.add(0).cast::<u8>() = (match success3 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    let vec4 = (message3.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
                        .cast_mut();
                    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (new_phase3
                        .clone() as i32) as u8;
                    *ptr2
                        .add(1 + 3 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match game_continues3 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_process_action<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l1 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_status_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                    arg11: *mut u8,
                    arg12: usize,
                    arg13: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg12;
                    let bytes0 = _rt::Vec::from_raw_parts(arg11.cast(), len0, len0);
                    let result1 = T::get_status(super::super::super::super::exports::docs::game_engine::types::GameState {
                        phase: super::super::super::super::exports::docs::game_engine::types::GamePhase::_lift(
                            arg0 as u8,
                        ),
                        player_x: arg1,
                        player_y: arg2,
                        player_health: arg3 as u32,
                        player_max_health: arg4 as u32,
                        player_attack: arg5 as u32,
                        player_defense: arg6 as u32,
                        player_level: arg7 as u32,
                        player_exp: arg8 as u32,
                        enemies_defeated: arg9 as u32,
                        boss_defeated: _rt::bool_lift(arg10 as u8),
                        current_area: _rt::string_lift(bytes0),
                        turn_number: arg13 as u32,
                    });
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_status<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_check_encounter_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                    arg6: i32,
                    arg7: i32,
                    arg8: i32,
                    arg9: i32,
                    arg10: i32,
                    arg11: *mut u8,
                    arg12: usize,
                    arg13: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg12;
                    let bytes0 = _rt::Vec::from_raw_parts(arg11.cast(), len0, len0);
                    let result1 = T::check_encounter(super::super::super::super::exports::docs::game_engine::types::GameState {
                        phase: super::super::super::super::exports::docs::game_engine::types::GamePhase::_lift(
                            arg0 as u8,
                        ),
                        player_x: arg1,
                        player_y: arg2,
                        player_health: arg3 as u32,
                        player_max_health: arg4 as u32,
                        player_attack: arg5 as u32,
                        player_defense: arg6 as u32,
                        player_level: arg7 as u32,
                        player_exp: arg8 as u32,
                        enemies_defeated: arg9 as u32,
                        boss_defeated: _rt::bool_lift(arg10 as u8),
                        current_area: _rt::string_lift(bytes0),
                        turn_number: arg13 as u32,
                    });
                    match result1 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_help_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_help();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_help<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    /// Process a player action and return the result.
                    fn process_action(
                        state: GameState,
                        action: GameAction,
                    ) -> ActionResult;
                    /// Get the current game state as a formatted string.
                    fn get_status(state: GameState) -> _rt::String;
                    /// Check for enemy encounters after movement.
                    fn check_encounter(state: GameState) -> bool;
                    /// Get help text for available actions.
                    fn get_help() -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_docs_game_engine_engine_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "docs:game-engine/engine@0.1.0#process-action")] unsafe extern
                        "C" fn export_process_action(arg0 : i32, arg1 : i32, arg2 : i32,
                        arg3 : i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8
                        : i32, arg9 : i32, arg10 : i32, arg11 : * mut u8, arg12 : usize,
                        arg13 : i32, arg14 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_process_action_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                        arg11, arg12, arg13, arg14) } } #[unsafe (export_name =
                        "cabi_post_docs:game-engine/engine@0.1.0#process-action")] unsafe
                        extern "C" fn _post_return_process_action(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_process_action::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "docs:game-engine/engine@0.1.0#get-status")] unsafe extern "C" fn
                        export_get_status(arg0 : i32, arg1 : i32, arg2 : i32, arg3 : i32,
                        arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8 : i32, arg9
                        : i32, arg10 : i32, arg11 : * mut u8, arg12 : usize, arg13 :
                        i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_status_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) } }
                        #[unsafe (export_name =
                        "cabi_post_docs:game-engine/engine@0.1.0#get-status")] unsafe
                        extern "C" fn _post_return_get_status(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_get_status::<$ty > (arg0) }
                        } #[unsafe (export_name =
                        "docs:game-engine/engine@0.1.0#check-encounter")] unsafe extern
                        "C" fn export_check_encounter(arg0 : i32, arg1 : i32, arg2 : i32,
                        arg3 : i32, arg4 : i32, arg5 : i32, arg6 : i32, arg7 : i32, arg8
                        : i32, arg9 : i32, arg10 : i32, arg11 : * mut u8, arg12 : usize,
                        arg13 : i32,) -> i32 { unsafe { $($path_to_types)*::
                        _export_check_encounter_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) }
                        } #[unsafe (export_name =
                        "docs:game-engine/engine@0.1.0#get-help")] unsafe extern "C" fn
                        export_get_help() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_get_help_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_docs:game-engine/engine@0.1.0#get-help")] unsafe
                        extern "C" fn _post_return_get_help(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_get_help::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_game_engine_engine_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// World and map interface.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod game_world {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type TileType = super::super::super::super::exports::docs::game_engine::types::TileType;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_tile_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_tile(arg0, arg1);
                    result0.clone() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_is_walkable_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::is_walkable(arg0, arg1);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_area_name_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_area_name(arg0, arg1);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_area_name<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_has_event_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::has_event(arg0, arg1);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                pub trait Guest {
                    /// Get the tile type at a position.
                    fn get_tile(x: i32, y: i32) -> TileType;
                    /// Check if a position is walkable.
                    fn is_walkable(x: i32, y: i32) -> bool;
                    /// Get the name of the current area.
                    fn get_area_name(x: i32, y: i32) -> _rt::String;
                    /// Check if position has a special event.
                    fn has_event(x: i32, y: i32) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_docs_game_engine_game_world_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "docs:game-engine/game-world@0.1.0#get-tile")] unsafe extern "C"
                        fn export_get_tile(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_get_tile_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name =
                        "docs:game-engine/game-world@0.1.0#is-walkable")] unsafe extern
                        "C" fn export_is_walkable(arg0 : i32, arg1 : i32,) -> i32 {
                        unsafe { $($path_to_types)*:: _export_is_walkable_cabi::<$ty >
                        (arg0, arg1) } } #[unsafe (export_name =
                        "docs:game-engine/game-world@0.1.0#get-area-name")] unsafe extern
                        "C" fn export_get_area_name(arg0 : i32, arg1 : i32,) -> * mut u8
                        { unsafe { $($path_to_types)*:: _export_get_area_name_cabi::<$ty
                        > (arg0, arg1) } } #[unsafe (export_name =
                        "cabi_post_docs:game-engine/game-world@0.1.0#get-area-name")]
                        unsafe extern "C" fn _post_return_get_area_name(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_get_area_name::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "docs:game-engine/game-world@0.1.0#has-event")] unsafe extern "C"
                        fn export_has_event(arg0 : i32, arg1 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_has_event_cabi::<$ty > (arg0, arg1)
                        } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_docs_game_engine_game_world_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_game_engine_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::docs::game_engine::types::__export_docs_game_engine_types_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::game_engine::types);
        $($path_to_types_root)*::
        exports::docs::game_engine::init::__export_docs_game_engine_init_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::game_engine::init);
        $($path_to_types_root)*::
        exports::docs::game_engine::engine::__export_docs_game_engine_engine_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::game_engine::engine);
        $($path_to_types_root)*::
        exports::docs::game_engine::game_world::__export_docs_game_engine_game_world_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::docs::game_engine::game_world);
    };
}
#[doc(inline)]
pub(crate) use __export_game_engine_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:docs:game-engine@0.1.0:game-engine:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1343] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbd\x09\x01A\x02\x01\
A\x0d\x01B\x0a\x01m\x0a\x0amove-north\x0amove-south\x09move-east\x09move-west\x06\
attack\x08use-item\x0eopen-inventory\x08interact\x04wait\x04quit\x04\0\x0bgame-a\
ction\x03\0\0\x01m\x07\x0bexploration\x06combat\x09inventory\x08dialogue\x06paus\
ed\x09game-over\x07victory\x04\0\x0agame-phase\x03\0\x02\x01r\x04\x07success\x7f\
\x07messages\x09new-phase\x03\x0egame-continues\x7f\x04\0\x0daction-result\x03\0\
\x04\x01r\x0d\x05phase\x03\x08player-xz\x08player-yz\x0dplayer-healthy\x11player\
-max-healthy\x0dplayer-attacky\x0eplayer-defensey\x0cplayer-levely\x0aplayer-exp\
y\x10enemies-defeatedy\x0dboss-defeated\x7f\x0ccurrent-areas\x0bturn-numbery\x04\
\0\x0agame-state\x03\0\x06\x01m\x08\x05grass\x04wall\x05water\x06forest\x10dunge\
on-entrance\x04shop\x05chest\x03npc\x04\0\x09tile-type\x03\0\x08\x04\0\x1cdocs:g\
ame-engine/types@0.1.0\x05\0\x02\x03\0\0\x0agame-state\x01B\x06\x02\x03\x02\x01\x01\
\x04\0\x0agame-state\x03\0\0\x01@\0\0\x01\x04\0\x08new-game\x01\x02\x01@\x01\x05\
state\x01\0\x7f\x04\0\x0evalidate-state\x01\x03\x04\0\x1bdocs:game-engine/init@0\
.1.0\x05\x02\x02\x03\0\0\x0bgame-action\x02\x03\0\0\x0daction-result\x02\x03\0\0\
\x0agame-phase\x01B\x10\x02\x03\x02\x01\x03\x04\0\x0bgame-action\x03\0\0\x02\x03\
\x02\x01\x04\x04\0\x0daction-result\x03\0\x02\x02\x03\x02\x01\x01\x04\0\x0agame-\
state\x03\0\x04\x02\x03\x02\x01\x05\x04\0\x0agame-phase\x03\0\x06\x01@\x02\x05st\
ate\x05\x06action\x01\0\x03\x04\0\x0eprocess-action\x01\x08\x01@\x01\x05state\x05\
\0s\x04\0\x0aget-status\x01\x09\x01@\x01\x05state\x05\0\x7f\x04\0\x0fcheck-encou\
nter\x01\x0a\x01@\0\0s\x04\0\x08get-help\x01\x0b\x04\0\x1ddocs:game-engine/engin\
e@0.1.0\x05\x06\x02\x03\0\0\x09tile-type\x01B\x0b\x02\x03\x02\x01\x07\x04\0\x09t\
ile-type\x03\0\0\x02\x03\x02\x01\x01\x04\0\x0agame-state\x03\0\x02\x01@\x02\x01x\
z\x01yz\0\x01\x04\0\x08get-tile\x01\x04\x01@\x02\x01xz\x01yz\0\x7f\x04\0\x0bis-w\
alkable\x01\x05\x01@\x02\x01xz\x01yz\0s\x04\0\x0dget-area-name\x01\x06\x04\0\x09\
has-event\x01\x05\x04\0!docs:game-engine/game-world@0.1.0\x05\x08\x04\0\"docs:ga\
me-engine/game-engine@0.1.0\x04\0\x0b\x11\x01\0\x0bgame-engine\x03\0\0\0G\x09pro\
ducers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
